version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: yetumia-frontend
    ports:
      - "80"
    volumes:
      - .:/usr/share/nginx/html
    restart: unless-stopped

